apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.eService.name }}
  labels:
    app: {{ .Values.eService.name }}
    version: "{{ .Values.eService.image | regexFind "\\d+\\.\\d+\\.\\d+" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.eService.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Values.eService.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.eService.name }}
        version: "{{ .Values.eService.image | regexFind "\\d+\\.\\d+\\.\\d+" }}"
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.eService.name }}
          image: "{{ .Values.eService.image }}"
          imagePullPolicy: {{ .Values.eService.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.eService.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.eService.resources | indent 12 }}
    {{- with .Values.eService.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.eService.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.eService.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
