environment: dev

eService:
  name: eservice
  replicaCount: 1
  port: 80
  image: birdmodify/birdtest-webapp:20211203-9
  pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80
  resources:
    limits:  
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 256Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
